# Generated by Django 4.0 on 2021-12-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_request_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remark',
            name='doctor_remark',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='remark',
            name='system_remark',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
